-- TODO: DELETE. DEV ONLY.

DROP TABLE Locations CASCADE CONSTRAINTS;
DROP TABLE UserProfile CASCADE CONSTRAINTS;
DROP TABLE TouristAttractions1 CASCADE CONSTRAINTS;
DROP TABLE TouristAttractions2 CASCADE CONSTRAINTS;
DROP TABLE Transportation CASCADE CONSTRAINTS;
DROP TABLE ServicedBy CASCADE CONSTRAINTS;
DROP TABLE ExperienceOffered CASCADE CONSTRAINTS;
DROP TABLE Booking1 CASCADE CONSTRAINTS;
DROP TABLE Booking2 CASCADE CONSTRAINTS;
DROP TABLE Responses CASCADE CONSTRAINTS;
DROP TABLE Reviews CASCADE CONSTRAINTS;
DROP TABLE Comments CASCADE CONSTRAINTS;
DROP TABLE Photos CASCADE CONSTRAINTS;

COMMIT;